import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

const CreatePostWizard = () => {
  const { user } = useUser();
  if (!user) return null;
  return (
    <div className="flex w-full gap-3">
      <img className="w-14 h-14 rounded-full" src={user.profileImageUrl} alt="Profile Image"/>
      <input className="bg-transparent grow outline-none" placeholder="Type some emojis..." />
    </div>
  );
}

export default function Home() {
  const { data, isLoading } = api.posts.getAll.useQuery();
  const user = useUser();

  if(isLoading) return <div>Loadig...</div>
  if(!data) return <div>Something went wrong...</div>
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full h-full border-x md:max-w-2xl border-slate-400">
          <div className="border-b border-slate-100 p-4 flex ">
            {!user.isSignedIn? 
                <div className="flex justify-center ">
                  <SignInButton mode="modal"/>
                </div>
              :
                <div className="flex justify-center w-full">
                  <CreatePostWizard />
                </div>
            }
          </div>
          {/* data?.map((post) */}
          {[...data, ...data].map(({post, author}) => (
            <div className="p-8 border-b border-slate-400" key={`${post.id}${Math.random()}`}>
              {post.content}
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
